// src/components/home-page/TechStack.vue
<template>
  <ZigZagLine class="float-left move-animation-2" :opacity="1"></ZigZagLine>
  <div class="app-padding py-15 my-15" :style="style">
    <SectionHeader :title="title" :subtitle="subtitle" />
    <circle-outline
      class="move-animation-3 float-right"
      :opacity="0.8"
      :stroke="'#1F7949'"
      style="width: 15px"
    />
    <v-row align="end" justify="center" no-gutters>
      <v-col
        cols="4"
        xs="4"
        sm="4"
        md="2"
        lg="2"
        xl="2"
        class="justify-center text-center"
        v-for="(skill, i) in tech_stacks"
        :key="i"
      >
        <div
          class="skills-card align-center text-center pa-md-4 pa-2 ma-md-4 ma-1"
          :style="{ '--data-index': i % 2 == 0 ? i : i / 4 }"
        >
          <div class="mt-4">
            <img
              :src="skill.img"
              :alt="skill.title"
              width="70"
              :style="{ '--data-index': i % 2 == 0 ? i : i / 4 }"
            />
            <p class="mt-3" v-html="skill.title"></p>
          </div>
        </div>
      </v-col>
    </v-row>
  </div>
</template>
<!--  -->
<style lang="scss" scoped>
.skills-card {
  background-color: rgb(var(--v-theme-primary), 0.06);
  border-radius: 5px;
  transition-duration: 1s;

  p {
    color: rgb(var(--v-theme-stroke-1));
    transform-origin: bottom;
    animation: text_animate 5s cubic-bezier(0.9, 0.03, 0.69, 0.22)
      calc(3s * var(--data-index)) alternate infinite;
  }

  img {
    background-clip: transparent;
    transform-origin: top;
    filter: grayscale(10);
    animation: img_animate 5s cubic-bezier(0.9, 0.03, 0.69, 0.22)
      calc(3s * var(--data-index)) alternate infinite;
  }
}

@keyframes img_animate {
  0%,
  30%,
  90%,
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -ms-transform: scale(1); /* IE 9 */
    -webkit-transform: scale(1);
    filter: none;
    filter: grayscale(10);
  }
  40%,
  50%,
  60% {
    -webkit-transform: scale(1.4);
    transform: scale(1.4);
    -ms-transform: scale(1.4); /* IE 9 */
    -webkit-transform: scale(1.4);
    filter: none;
  }
}
@keyframes text_animate {
  0%,
  30%,
  90%,
  100% {
    opacity: 1;
  }
  40%,
  50%,
  60% {
    opacity: 0.01;
  }
}
</style>
<!--   -->
<script setup>
let title = "Tech Stack";
let subtitle = "Power of technology ##in my hands";
let description = "";
let tech_stacks = [
  {
    title: "Python",
    img: new URL("@/assets/images/tech-stack/python.png", import.meta.url).href,
  },
  {
    title: "Django",
    img: new URL("@/assets/images/tech-stack/django.png", import.meta.url).href,
  },
  {
    title: "Vue js",
    img: new URL("@/assets/images/tech-stack/vue.png", import.meta.url).href,
  },
  {
    title: "Vuetify",
    width: 45,
    img: new URL("@/assets/images/tech-stack/vuetify.png", import.meta.url).href,
  },
  {
    title: "Nuxt",
    width: 45,
    img: new URL("@/assets/images/tech-stack/nuxt.png", import.meta.url).href,
  },
  {
    title: "Javascript",
    img: new URL("@/assets/images/tech-stack/js.png", import.meta.url).href,
  },
  {
    title: "Git",
    img: new URL("@/assets/images/tech-stack/git.png", import.meta.url).href,
  },
  {
    title: "React",
    img: new URL("@/assets/images/tech-stack/react.png", import.meta.url).href,
  },
  {
    title: "React Native",
    img: new URL("@/assets/images/tech-stack/react.png", import.meta.url).href,
  },
  {
    title: "Next.js",
    img: new URL("@/assets/images/tech-stack/nextjs.png", import.meta.url).href,
  },
  {
    title: "Jquery",
    img: new URL("@/assets/images/tech-stack/jquery.png", import.meta.url).href,
  },
  {
    title: "HTML5",
    img: new URL("@/assets/images/tech-stack/html.png", import.meta.url).href,
  },
  {
    title: "SASS",
    img: new URL("@/assets/images/tech-stack/sass.png", import.meta.url).href,
  },
  {
    title: "Mysql",
    img: new URL("@/assets/images/tech-stack/mysql.png", import.meta.url).href,
  },
  {
    title: "Postgresql",
    img: new URL("@/assets/images/tech-stack/postgres.png", import.meta.url).href,
  },
  {
    title: "Figma",
    img: new URL("@/assets/images/tech-stack/figma.png", import.meta.url).href,
  },
  {
    title: "AWS",
    img: new URL("@/assets/images/tech-stack/aws.png", import.meta.url).href,
  },
  {
    title: "firebase",
    img: new URL("@/assets/images/tech-stack/firebase.png", import.meta.url).href,
  },
  {
    title: "Nginx",
    img: new URL("@/assets/images/tech-stack/nginx.png", import.meta.url).href,
  },
  {
    title: "Ubuntu",
    img: new URL("@/assets/images/tech-stack/ubuntu.png", import.meta.url).href,
  },
  {
    title: "OpenAI GPT",
    img: new URL("@/assets/images/tech-stack/gpt.png", import.meta.url).href,
  },
  {
    title: "Claude AI",
    img: new URL("@/assets/images/tech-stack/claude.png", import.meta.url).href,
  },
  {
    title: "GitHub Copilot",
    img: new URL("@/assets/images/tech-stack/github-copilot.png", import.meta.url).href,
  },
  {
    title: "Midjourney",
    img: new URL("@/assets/images/tech-stack/mid-journey.png", import.meta.url).href,
  },
  {
    title: "Gemini",
    img: new URL("@/assets/images/tech-stack/gemini.png", import.meta.url).href,
  },
];
const getImageUrl = (path) => {
  return new URL(`${path}`, import.meta.url).href;
};
</script>

// src/components/sections/tech-stack.tsx
"use client"

import { motion } from "framer-motion"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import Image from "next/image"
import { useTheme } from "next-themes"

const getTechCategories = (isDark: boolean) => [
    {
        category: "Frontend",
        technologies: [
            { name: "Next.js", image: isDark ? "./images/tech-stack/nextjs.png" : "./images/tech-stack/nextjs-black.png" },
            { name: "React", image: "./images/tech-stack/react.png" },
            { name: "Vue.js", image: "./images/tech-stack/vue.png" },
            { name: "JavaScript", image: "./images/tech-stack/js.png" },
            { name: "HTML5", image: "./images/tech-stack/html.png" },
            { name: "SASS", image: "./images/tech-stack/sass.png" },
            { name: "Nuxt.js", image: "./images/tech-stack/nuxt.png" },
            { name: "Vuetify", image: "./images/tech-stack/vuetify.png" },
            { name: "jQuery", image: "./images/tech-stack/jquery.png" },
        ]
    },
    {
        category: "Backend & Database",
        technologies: [
            { name: "Python", image: "./images/tech-stack/python.png" },
            { name: "Django", image: "./images/tech-stack/django.png" },
            { name: "PostgreSQL", image: "./images/tech-stack/postgres.png" },
            { name: "MySQL", image: "./images/tech-stack/mysql.png" },
            { name: "Firebase", image: "./images/tech-stack/firebase.png" },
        ]
    },
    {
        category: "DevOps & Tools",
        technologies: [
            { name: "Git", image: "./images/tech-stack/git.png" },
            { name: "AWS", image: isDark ? "./images/tech-stack/aws.png" : "./images/tech-stack/aws-black.png" },
            { name: "Ubuntu", image: "./images/tech-stack/ubuntu.png" },
            { name: "Nginx", image: "./images/tech-stack/nginx.png" },
            { name: "Figma", image: "./images/tech-stack/figma.png" },
        ]
    },
    {
        category: "AI & Design",
        technologies: [
            { name: "Claude", image: "./images/tech-stack/claude.png" },
            { name: "GPT", image: "./images/tech-stack/gpt.png" },
            { name: "Gemini", image: "./images/tech-stack/gemini.png" },
            { name: "GitHub Copilot", image: isDark ? "./images/tech-stack/github-copilot.png" : "./images/tech-stack/github-copilate-black.png" },
            { name: "Midjourney", image: isDark ? "./images/tech-stack/mid-journey.png" : "./images/tech-stack/mid-journey-black.png" },
        ]
    }
]

const TechCard = ({ tech, index }: { tech: { name: string, image: string }, index: number }) => (
    <motion.div
        initial={{ opacity: 0, scale: 0.8 }}
        whileInView={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5, delay: index * 0.05 }}
        viewport={{ once: true }}
        whileHover={{ scale: 1.05 }}
        className="group"
    >
        <Card className="card-hover dark:bg-card/50 dark:border-border/30 dark:hover:border-primary/30 dark:hover:bg-card/70">
            <CardContent className="p-6 text-center">
                <div className="relative w-16 h-16 mx-auto mb-4 image-overlay">
                    <Image
                        src={tech.image}
                        alt={tech.name}
                        fill
                        className="object-contain transition-transform duration-300 group-hover:scale-110"
                        sizes="64px"
                    />
                </div>
                <Badge variant="secondary" className="text-sm font-medium dashed-outline">
                    {tech.name}
                </Badge>
            </CardContent>
        </Card>
    </motion.div>
)

export function TechStack() {
    const { theme } = useTheme()
    const isDark = theme === 'dark'
    const techCategories = getTechCategories(isDark)

    return (
        <section id="tech-stack" className="py-20 bg-muted/30 dark:bg-muted/10">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <motion.div
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8 }}
                    viewport={{ once: true }}
                    className="text-center mb-16"
                >
                    <Badge variant="secondary" className="mb-4">
                        Technologies
                    </Badge>
                    <h2 className="text-4xl md:text-5xl font-bold mb-6 dark:text-foreground">
                        Tech Stack & Tools
                    </h2>
                    <p className="text-xl text-muted-foreground dark:text-muted-foreground/80 max-w-3xl mx-auto">
                        I work with a diverse set of technologies and tools to build
                        scalable, efficient, and user-friendly applications.
                    </p>
                </motion.div>

                <div className="space-y-12">
                    {techCategories.map((category, categoryIndex) => (
                        <motion.div
                            key={category.category}
                            initial={{ opacity: 0, y: 30 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: categoryIndex * 0.1 }}
                            viewport={{ once: true }}
                        >
                            <h3 className="text-2xl font-bold text-center mb-8 dark:text-foreground">
                                {category.category}
                            </h3>
                            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
                                {category.technologies.map((tech, techIndex) => (
                                    <TechCard
                                        key={tech.name}
                                        tech={tech}
                                        index={categoryIndex * 10 + techIndex}
                                    />
                                ))}
                            </div>
                        </motion.div>
                    ))}
                </div>

                {/* Skills overview */}
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8, delay: 0.4 }}
                    viewport={{ once: true }}
                    className="mt-20"
                >
                    <Card className="bg-background dark:bg-card/50 card-hover dark:border-border/30">
                        <CardContent className="p-8 md:p-12">
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 text-center">
                                <div className="group">
                                    <h4 className="text-4xl font-bold text-primary dark:text-primary mb-2 group-hover:scale-110 transition-transform">6+</h4>
                                    <p className="text-muted-foreground dark:text-muted-foreground/80 font-medium">Years Experience</p>
                                </div>
                                <div className="group">
                                    <h4 className="text-4xl font-bold text-primary dark:text-primary mb-2 group-hover:scale-110 transition-transform">20+</h4>
                                    <p className="text-muted-foreground dark:text-muted-foreground/80 font-medium">Technologies Mastered</p>
                                </div>
                                <div className="group">
                                    <h4 className="text-4xl font-bold text-primary dark:text-primary mb-2 group-hover:scale-110 transition-transform">15+</h4>
                                    <p className="text-muted-foreground dark:text-muted-foreground/80 font-medium">Projects Completed</p>
                                </div>
                                <div className="group">
                                    <h4 className="text-4xl font-bold text-primary dark:text-primary mb-2 group-hover:scale-110 transition-transform">24/7</h4>
                                    <p className="text-muted-foreground dark:text-muted-foreground/80 font-medium">Always Learning</p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </motion.div>
            </div>
        </section>
    )
}
